### ISSUE TITLE
Async assertion failure exits grunt in Fatal error

### ISSUE THREAD

**Issue by Bartvds** [jdavis/grunt-cafe-mocha#3]
If you paste this in the test and run grunt it will exit instantly on a Fatal error:

```
it('async fails', function (done) {
    process.nextTick(function () {
        (1).should.equal(1000);
        done();
    });
});
```

**Comment by Bartvds** [comment]
It seems more server-side grunt + mocha plugins suffer from this: https://github.com/yaymukund/grunt-simple-mocha/issues/16

**Comment by RomanMinkin** [comment]
Hi!

Just tested with `Node.js v0.10.12`, `mocha@1.12.0`, `grunt-cafe-mocha@0.1.8`, `grunt@0.4.1`, `should@1.2.2` all good. No error anymore.

**Comment by RomanMinkin** [comment]
Nope, i was wrong =(

**Comment by Bartvds** [comment]
Haha, nice ;)

I now use https://github.com/pghalliday/grunt-mocha-test. It's fully featured, properly tested and actively maintained.

**Comment by jdavis** [comment]
Ouch :(

**Comment by devenv** [comment]
Thanks @Bartvds - using grunt-mocha-test now too :)
Waiting for a fix though...

**Comment by jdavis** [comment]
Yeah, please do use grunt-mocha-test. I'm not maintaining this one as I haven't been using Node/Grunt much. I may make a notice on the README.
