### ISSUE TITLE
options.colors Fails with Warning

### ISSUE THREAD

**Issue by joshuarubin** [jdavis/grunt-cafe-mocha#4]
```
Warning: Cannot set property 'useColors' of undefined Use --force to continue.
```

To fix, in tasks/cafe_mocha.js, just replace Mocha.reporters.base with Mocha.reporters.Base

**Comment by jdavis** [comment]
Nice find! I'll fix it as soon as I get home and publish it to NPM.

**Comment by jdavis** [comment]
Doh, I really need to close these issues in my commit message. It has been updated though with commit 89c9b7fa12b01dd1b3799913b7b43190d71d8429 and then updated to version 0.1.5

The latest is on NPM as well, just do a:

``` bash
$ npm update grunt-cafe-mocha
```

**Comment by joshuarubin** [comment]
Thanks for taking care of this so quickly!

**Comment by jdavis** [comment]
Thanks for reporting it!
