### ISSUE TITLE
js-cov doesn't exist in mocha

### ISSUE THREAD

**Issue by pocesar** [jdavis/grunt-cafe-mocha#6]
the reporter is actually `json-cov`, just found out :+1:

**Comment by jdavis** [comment]
Awesome. Just fixed it with commit 7cde10e609d4e48d175f179cf068afd19d1d4aef. The funny thing is that the documentation was right, just not the code. Usually it is the other way around :P. Also, maybe I need to make better tests... Haha.

**Comment by pocesar** [comment]
yeah lol. thanks for making this library, the other mocha grunt tasks are always focused on client-side, and this is the only one that actually works (like the saying!)

**Comment by jdavis** [comment]
No problem. Thanks for opening these issues too by the way. In some aspects, open source is only as great as it is because of users like you.

**Comment by pocesar** [comment]
:+1:
